blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse

def log(request):
    return HttpResponse('test')


urlpatterns = [
    path('admin/', admin.site.urls),
    #include的参数中,我们首先来设置一个元组 urlconf_module,app_name
    # urlconf_module 子应用的路由
    # app_name  子应用的函数名
    # namespace 命名空间
    path('',include(('users.urls','users'),namespace='users')),
    # path('',log),
    path('',include(('home.urls','home'),namespace='home')),
]


# 图片访问的路由
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/home/urls.py
"""
@Time ： 2021/12/12 20:10
@Auth ： 021321752215舒洪凡
@File ：urls.py
@IDE ：PyCharm
"""
from django.urls import path
from home.views import IndexView, DetailView

urlpatterns = [
    # 首页的路由
    path("",IndexView.as_view(),name='index'),
    # 详情视图的路由
    path('detail/',DetailView.as_view(),name='detail')
]

blog/users/urls.py
"""
@Time ： 2021/12/12 14:52
@Auth ： 021321752215舒洪凡
@File ：urls.py
@IDE ：PyCharm
"""

# 进行users子应用的视图路由
from django.urls import path
from users.views import RegisterView, ImageCodeView, LoginView, LogoutView, UserCenterView, WriteBlogView, \
    ResetPasswordView, DeleteBlogView

urlpatterns = [
    # path的路由
    #     第一个参数: 路由
    #     path的第二个参数: 视图函数名
    path('register/',RegisterView.as_view(),name='register'),

    # 图片验证码的路由
    path('imagecode/',ImageCodeView.as_view(),name='imagecode'),

    # 登录路由
    path("login/",LoginView.as_view(),name="login"),

    # 退出登录
    path("logout/",LogoutView.as_view(),name="logout"),

    # 个人中心
    path("center/",UserCenterView.as_view(),name="center"),

    # 写博客的路由
    path("writeblog/",WriteBlogView.as_view(),name="writeblog"),

    # 删除博客
    path("deleteblog/",DeleteBlogView.as_view(),name="deleteblog"),

    # 重置密码
    path("resetpassword/",ResetPasswordView.as_view(),name="resetpassword")
]

blog/templates/center.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
{% load static %}
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title> 用户信息 </title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>

<body>
<div id="app">

<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="container">
        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="{% url 'home:index' %}">
            <img src="{% static 'img/SHF.PNG' %}" alt="logo" style="width:40px;">
        </a>
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">博客Blog</a>
        </div>
        <!-- 分类 -->
        <div class="collapse navbar-collapse">
           <ul class="nav navbar-nav navbar-left">
                    {% for cat in categories %}
                        {% if cat.id == category.id %}
                            <li class="nav-item active">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% else %}
                             <li class="nav-item">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            <ul class="nav navbar-nav navbar-right" style="position: relative;right: -25rem;">
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown" v-if="is_login">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">[[username]]</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                        <a class="dropdown-item" href="{% url 'users:writeblog' %}">写文章</a>
                        <a class="dropdown-item" href='{% url 'users:center' %}'>个人信息</a>
                        <a class="dropdown-item" href='{% url 'users:resetpassword' %}'>重置密码</a>
                        <a class="dropdown-item" href='{% url 'users:logout' %}'>退出登录</a>
                    </div>
                </li>
                <!-- 如果用户未登录，则显示登录按钮 -->
                <li class="nav-item" v-else>
                    <a class="nav-link"  href="{% url 'users:login' %}">登录</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!--content-->
<div class="container" style="margin-bottom: 20px">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <!-- username -->
                <div class="form-group col-md-4">
                    <label for="username">用户名</label>
                    <input type="text" class="form-control" id="username" name="username" value="{{ username }}" >
                </div>
                <!--<br><h5 class="col-md-4">暂无头像</h5><br>-->
                <br> <div class="col-md-4">头像</div>
                    {% if avatar %}
                        <img src="{{ avatar }}" style="max-width: 20%;" class="col-md-4"><br>
                    {% else %}
                        <img src="{% static 'img/mei.png' %}" style="max-width: 20%;" class="col-md-4"><br>
                    {% endif %}
                    <!-- avatar -->
                    <div class="form-group col-md-4">
                        <label for="avatar">上传头像</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>

                    <!-- phone -->
                    <div class="form-group col-md-4">
                        <label for="phone">电话</label>
                        <input type="text" class="form-control" disabled="disabled" id="phone" name="phone" value="{{ mobile }}">
                    </div>
                    <!-- desc -->
                    <div class="form-group col-md-4">
                        <label for="desc">简介</label>
                        <!-- 文本区域 -->
                        <textarea type="text" class="form-control" id="desc" name="desc" rows="12" >{{ user_desc }}</textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary" style="margin-left: 12px" >修改</button>
                </form>
            </div>
        </div>
    </div>


<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ shuhongfan</h5>
    </div>
</footer>
</div>
<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/center.js' %}"></script>
</body>

</html>

blog/templates/detail.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
{% load static %}
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>文章详情</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!--详情页面导入-->
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'prism/prism.css' %}../static/">
    <!--导入css-->
    <link rel="stylesheet" href="{% static 'common/common.css' %}">
    <link rel="stylesheet" href="{% static 'common/jquery.pagination.css' %}">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
</head>

<body>
<div id="app">
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="container">
        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="{% url 'home:index' %}">
            <img src="{% static 'img/SHF.PNG' %}" alt="logo" style="width:40px;">
        </a>
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">博客Blog</a>
        </div>
        <!-- 分类 -->
        <div class="collapse navbar-collapse">
           <ul class="nav navbar-nav navbar-left">
                    {% for cat in categories %}
                        {% if cat.id == category.id %}
                            <li class="nav-item active">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% else %}
                             <li class="nav-item">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            <ul class="nav navbar-nav navbar-right" style="position: relative;right: -25rem;">
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown" v-if="is_login">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">[[username]]</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                        <a class="dropdown-item" href="{% url 'users:writeblog' %}">写文章</a>
                        <a class="dropdown-item" href='{% url 'users:center' %}'>个人信息</a>
                        <a class="dropdown-item" href='{% url 'users:resetpassword' %}'>重置密码</a>
                        <a class="dropdown-item" href='{% url 'users:logout' %}'>退出登录</a>
                    </div>
                </li>
                <!-- 如果用户未登录，则显示登录按钮 -->
                <li class="nav-item" v-else>
                    <a class="nav-link"  href="{% url 'users:login' %}">登录</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- content -->
<div class="container">
    <div class="row">
        <!--文章详情-->
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>作者：<span>{{ article.author.username }}</span></div>
                <div>浏览：{{ article.total_views }}</div>
                <!-- 删除博客 -->
                {% if article.author.username == username  %}
                    <a href="{% url 'users:deleteblog' %}?articleID={{ id }}" class="btn btn-primary ">删除博客</a>
                {% endif %}
            </div>
            <!-- 文章正文 -->
            <div class="col-12" style="word-break: break-all;word-wrap: break-word;">
                <p><p>{{ article.content | safe }}</p></p>
            </div>
            <br>
            <!-- 发表评论 -->
            <hr>
            <br>
            <h5 class="row justify-content-center" v-show="!is_login">请<a href="{% url 'users:login' %}">登录</a>后回复
            </h5>
            <br>
            <div>
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ article.id }}">
                <div class="form-group"><label for="body"><strong>我也要发言：</strong></label>
                    <div>

                        <div class="django-ckeditor-widget" data-field-id="id_body" style="display: inline-block;">
                            <textarea cols="40" id="id_body" name="content" rows="10" required data-processed="0" :data-config="data_config" data-external-plugin-resources="[]" data-id="id_body" data-type="ckeditortype">

                            </textarea>
                        </div>
                    </div>
                </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary ">发送</button>
                </form>
            </div>
            <br>
            <!-- 显示评论 -->
            <h4>共有{{ total_count }}条评论</h4>
            <div class="row">
                {% for comment in comments %}
                    <div class="col-12" >
                        <hr><p><strong style="color: pink"></strong></p>
                        <div>
                            <div><span><strong>{{ comment.user.username }}</strong></span>&nbsp;<span style="color: gray">{{ comment.created | date:'Y-m-d H:i' }}</span></div>
                            <br>
                            <p>{{ comment.content | safe }}</p>
                        </div>
                    </div>
                {% endfor %}
                <div class="pagenation" style="text-align: center">
                    <div id="pagination" class="page"></div>
                </div>
            </div> 

        </div>
        <!-- 推荐 -->
        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                    <h4><strong>推荐</strong></h4>
                    <hr>
                    {% for hot_articles in hot_articles %}
                        <a href="{% url 'home:detail' %}?id={{ hot_articles.id }}" style="color: black">{{ hot_articles.title }}</a><br>
                    {% endfor %}
            </div>
        </div>
    </div>
</div>


<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ shuhongfan</h5>
    </div>
</footer>
</div>

<!--ckeditor-->
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"
        data-ckeditor-basepath="{% static 'ckeditor/ckeditor/' %}" id="ckeditor-init-script"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/detail.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.pagination.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
            currentPage: {{ page_num }},
            totalPage: {{ total_page }},
            callback:function (current) {
                location.href = '/detail/?id={{ article.id }}&page_size={{ page_size }}&page_num='+current;
            }
        })
    });
</script>
</body>

</html>

blog/templates/index.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
{% load static %}
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>首页</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!--导入css-->
    <link rel="stylesheet" href="{% static 'common/common.css' %}">
    <link rel="stylesheet" href="{% static 'common/jquery.pagination.css' %}">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
</head>

<body>
<div id="app">
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="container">
        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="{% url 'home:index' %}">
            <img src="{% static 'img/SHF.PNG' %}" alt="logo" style="width:40px;">
        </a>
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">博客Blog</a>
        </div>
        <!-- 分类 -->
        <div class="collapse navbar-collapse">
           <ul class="nav navbar-nav navbar-left">
                    {% for cat in categories %}
                        {% if cat.id == category.id %}
                            <li class="nav-item active">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% else %}
                             <li class="nav-item">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            <ul class="nav navbar-nav navbar-right" style="position: relative;right: -25rem;">
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown" v-if="is_login">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">[[username]]</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                        <a class="dropdown-item" href="{% url 'users:writeblog' %}">写文章</a>
                        <a class="dropdown-item" href='{% url 'users:center' %}'>个人信息</a>
                        <a class="dropdown-item" href='{% url 'users:resetpassword' %}'>重置密码</a>
                        <a class="dropdown-item" href='{% url 'users:logout' %}'>退出登录</a>
                    </div>
                </li>
                <!-- 如果用户未登录，则显示登录按钮 -->
                <li class="nav-item" v-else>
                    <a class="nav-link"  href="{% url 'users:login' %}">登录</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- content -->
<div class="container">
    <!-- 列表循环 -->
    {% for article in page_articles %}
    <div class="row mt-2">
            <!-- 文章内容 -->
            <!-- 标题图 -->
            <div class="col-3">
                <img class="img-responsive" src="{{ article.avatar.url }}" alt="avatar" style="max-width:100%;max-height: 155px; border-radius: 20px">
            </div>
            <div class="col">
                <!-- 栏目 -->
                <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">{{ article.category.title }}</a>
            <!-- 标签 -->
                <span>
                        <a href="#" class="badge badge-secondary">{{ article.tags }}</a>
                </span>
                <!-- 标题 -->
                <h4>
                    <b><a href="{% url 'home:detail' %}?id={{ article.id }}" style="color: black;">{{ article.title }}</a></b>
                </h4>
                <!-- 摘要 -->
                <div>
                    <p style="color: gray;">
                       {{ article.sumary }}
                    </p>
                </div>
                <!-- 注脚 -->
                <p>
                    <!-- 查看、评论、时间 -->
                    <span><i class="fas fa-eye" style="color: lightskyblue;"></i>{{ article.total_views }}&nbsp;&nbsp;&nbsp;</span>
                    <span><i class="fas fa-comments" style="color: yellowgreen;"></i>{{ article.comments_count }}&nbsp;&nbsp;&nbsp;</span>
                    <span><i class="fas fa-clock" style="color: pink;"></i>{{ article.created | date }}</span>
                </p>
            </div>
            <hr style="width: 100%;"/>
    </div>
    {% endfor %}
    <!-- 页码导航 -->
    <div class="pagenation" style="text-align: center">
        <div id="pagination" class="page"></div>
    </div>
</div>

<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ shuhongfan</h5>
    </div>
</footer>
</div>

<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.pagination.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
            currentPage: {{ page_num }},
            totalPage: {{total_page}},
            callback:function (current) {
                location.href = '/?cat_id={{ category.id }}&page_size={{ page_size }}&page_num='+current;
            }
        })
    });
</script>
</body>
</html>

blog/templates/register.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
{% load static %}
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>注册</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js'%}"></script>
</head>
<body>
<div id="app">

<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="container">
        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="{% url 'home:index' %}">
            <img src="{% static 'img/SHF.PNG' %}" alt="logo" style="width:40px;">
        </a>
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">博客Blog</a>
        </div>
        <!-- 分类 -->
        <div class="collapse navbar-collapse">
           <ul class="nav navbar-nav navbar-left">
                    {% for cat in categories %}
                        {% if cat.id == category.id %}
                            <li class="nav-item active">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% else %}
                             <li class="nav-item">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            <ul class="nav navbar-nav navbar-right" style="position: relative;right: -25rem;">
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown" v-if="is_login">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">[[username]]</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                        <a class="dropdown-item" href="{% url 'users:writeblog' %}">写文章</a>
                        <a class="dropdown-item" href='{% url 'users:center' %}'>个人信息</a>
                        <a class="dropdown-item" href='{% url 'users:resetpassword' %}'>重置密码</a>
                        <a class="dropdown-item" href='{% url 'users:logout' %}'>退出登录</a>
                    </div>
                </li>
                <!-- 如果用户未登录，则显示登录按钮 -->
                <li class="nav-item" v-else>
                    <a class="nav-link"  href="{% url 'users:login' %}">登录</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!--content-->
<div class="container" style="height: 600px;margin-top: 20px">
    <div class="row" >
        <div class="col-12">
            <div class="col-6">
                <form class="login" id="login_form" method="POST">
                    {% csrf_token %}
                    <!--手机号-->
                    <div class="form-group">
                        <label >手机号: </label>
                        <div class="col-lg-6">
                            <input type="text" name="mobile" placeholder="请输入手机号" autofocus="autofocus" required
                                   id="id_login" class="form-control" v-model="mobile" />
                        </div>
                        <small class="form-text text-muted ml-1" v-show="mobile_error" >[[mobile_error_message]]</small>
                    </div>
                    <!--密码-->
                    <div class="form-group">
                        <label >密码:</label>
                        <div class="col-lg-6">
                            <input type="password" name="password" placeholder="请输入密码" required  class="form-control" v-model="password" @blur="check_password" />
                        </div>
                        <small class="form-text text-muted ml-1" v-show="password_error" >[[password_error_message]]</small>
                    </div>
                    <!--确认密码-->
                    <div class="form-group">
                        <label >确认密码:</label>
                        <div class="col-lg-6">
                            <input type="password" name="password2" placeholder="请输入确认密码" required  class="form-control" v-model="password2" @blur="check_password2"/>
                        </div>
                        <small class="form-text text-muted ml-1" v-show="password2_error" >[[password2_error_message]]</small>
                    </div>
                   <!--图片验证码-->
                    <div class="form-group">
                        <label >图片验证码:</label>
                        <div class="row" style="margin-right:5px;margin-left:0px">
                            <div class="col-lg-6">
                                <input type="text" name="imgage_code" placeholder="请输入图片验证码" required  class="form-control" v-model="image_code" @blur="check_image_code"/>
                            </div>
                            <img :src="image_code_url" @click="generate_image_code" alt="" style="width: 110px;height: 40px;">
                            <input style="opacity: 0" name="uuid" v-model="uuid">
                            <small class="form-text text-muted ml-1" v-show="image_code_error" >[[image_code_error_message]]</small>
                        </div>
                    </div>
                    <button class="primaryAction btn btn-primary" type="submit" id="submit_login" @click="on_submit">注册</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ shuhongfan</h5>
    </div>
</footer>
</div>
<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
</body>
</html>